import bcrypt from "bcrypt";
const data = {
	users: [
		{
			name: "Hieu",
			email: "ngphtrghieu1372@gmail.com",
			phone: "0123456",
			password: bcrypt.hashSync("1234", 8),
			isAdmin: true,
		},
		{
			name: "van Ha",
			email: "nguyenvanha@gmail.com",
			phone: "0123456",
			password: bcrypt.hashSync("1234", 8),
			isAdmin: false,
		},
	],
	products: [
		{
			name: "Hello Các Bạn Mình Là Tôi Đi Code Dạo",
			category: "Sách Bán Chạy",
			image: "/img/1.jpg",
			price: 165000,
			countInStock: 10,
			brand: "NXB Thanh Niên",
			rating: 0,
			numReviews: 0,
			description:
				"Hello Các Bạn Mình Là Tôi Đi Code Dạo Cho tới thời điểm hiện tại, IT vẫn đang là một ngành hot và là sự lựa chọn của rất nhiều các bạn học sinh, sinh viên. Tuy nhiên, cho đến nay, những nguồn tài nguyên học tập trong ngành còn quá ít. Ngoài những tài liệu học tập của trường học thì những tài liệu khác chủ yếu vẫn là các thông tin trên internet hoặc từ những kinh nghiệm của những người đi trước. Để bạn đọc có cái nhìn chân thực và rõ nét hơn về ngành IT, thông qua cuốn sách này, tác giả Phạm Huy Hoàng đã tóm tắt và chia sẻ lại những câu chuyện, bài học kinh nghiệm đã gặp, đã đúc rút được để bạn đọc tham khảo và tìm ra những điểm tương đồng với những gì mình gặp trong khi học tập và làm việc để từ đó rút ra được bài học cho riêng mình. Tôi Đi Code Dạo là một blog, fanpage và Youtube channel được sáng lập bởi Phạm Huy Hoàng - một full-stack developer đã tốt nghiệp Thạc sĩ ngành Computer Science tại Đại học Lancaster ở Anh (Học bổng 18.000 bảng) và hiện đang làm việc cho một startup công nghệ tại Singapore. Nội dung mà Tôi Đi Code Dạo chia sẻ một nửa là về kĩ thuật lập trình, một nửa còn lại là những kinh nghiệm mà Mr. Code Dạo đã học được như: cách deal lương, sắp xếp thời gian, kĩ năng mềm, ngôn ngữ lập trình nên học, con đường phát triển nghề nghiệp… Đó là những điều quan trọng không thua gì kĩ năng lập trình. \nPhương châm của Tôi Đi Code Dạo là: Developer cần biết nhiều điều hơn ngoài code, blog sẽ vừa dạy bạn code, vừa dạy bạn những điều còn lại. Hello các bạn, mình là tôi đi code dạo tổng hợp và chọn lọc hơn 60 bài viết trên blog của tác giả Phạm Huy Hoàng, chủ blog và fanpage Tôi đi code dạo. Cuốn sách hướng dẫn những kỹ năng mềm và những phần kỹ thuật thuần code, đồng thời chia sẻ những kinh nghiệm trong quá trình học tập và làm việc của tác giả. Hello các bạn, mình là Tôi Đi Code Dạo được tóm tắt khá ngắn gọn, lồng ghép một số câu chuyện vui để bạn đọc có thể cảm thấy thư giãn và tham khảo thêm thông tin một cách dễ dàng hơn. \nKhông chỉ là những kiến thức chuyên ngành khô khan, những câu chuyện đời, chuyện nghề rất thật và nhiều cảm xúc qua lối viết giản dị nhưng dí dỏm sẽ mang đến cho người đọc cảm giác gần gũi, dễ tiếp thu và đồng cảm. \nNếu bạn đã, đang và sẽ theo con đường lập trình viên thì đây chính là cuốn sách hữu ích dành cho bạn, giúp bạn có thêm những kỹ năng căn bản cũng như kinh nghiệm cần thiết trong hành trình theo đuổi ước mơ và nghề nghiệp của bản thân.",
		},
		{
			name: "How Money Works -Hiểu Hết Về Tiền (Tái bản 2022)",
			category: "Sách Bán Chạy",
			image: "/img/25.jpg",
			price: 300000,
			countInStock: 10,
			brand: "NXB Văn Học",
			rating: 0,
			numReviews: 0,
			description:
				"How Money Works - Hiểu Hết Về Tiền – Tập truyện ngắn chọn lọc của 3 tác giả họ Nguyễn cùng ở miền Đông: NGUYỄN MỘT, NGUYỄN TRÍ và NGUYỄN HIỆP. Mỗi tác giả góp mặt bằng 9 truyện ngắn đặc sắc với phong cách đặc trưng của riêng mình tạo thành “bản hòa tấu 27 chương” - vừa có sự hòa điệu, vừa thể hiện âm sắc độc đáo riêng của từng nhạc cụ. Truyện ngắn của Nguyễn Một thường có giọng điệu phóng khoáng và ẩn chứa tư duy thâm trầm, sâu sắc của nhà văn về những vấn đề nhân sinh. Ông thường khắc họa về mối quan hệ giữa sự sống và cái chết; khắc họa mối quan hệ gắn bó giữa tâm hồn con người và những dòng sông, các miền đất ông đã từng sinh sống. Cái nhìn của nhà văn hướng về sự đa chiều kích trong nội tâm, tính cách nhân vật. Thế giới nhân vật của Nguyễn Một thường có sự giằng xé, mâu thuẫn giữa thiện và ác, cái tầm thường và cái thiêng liêng, cao cả. Truyện ngắn của Nguyễn Trí thấm đẫm chất đời, chất bụi bặm và ẩn chứa chất “muối” của đời sống qua những chi tiết ngổn ngang, bề bộn. Ông thường khắc họa tính cách nhân vật thông qua biểu hiện của hành động, lời nói mà ít miêu tả diễn biến tâm trạng, nội tâm. Người đọc văn của Nguyễn Trí như được sống, trải nghiệm cùng thế giới nhân vật mà ông miêu tả. Theo tôi, Nguyễn Trí là nhà văn của những kiếp người lầm lạc nhưng vẫn giữ trong tâm hồn vẻ đẹp của lương tri và khát vọng sống.",
		},
		{
			name: "Thương Nhớ Miền Trung (Tái bản)",
			category: "Sách Bán Chạy",
			image: "/img/12.jpg",
			price: 90000,
			countInStock: 20,
			brand: "NXB Hồng Đức",
			rating: 0,
			numReviews: 0,
			description:
				"NHỮNG BÀI ĐOẠT GIẢI VÀ TIÊU BIỂU TỪ CUỘC THI VIẾT “THƯƠNG NHỚ MIỀN TRUNG” CỦA BÁO THANH NIÊN 2020",
		},
		{
			name: "Phải Lòng Với Cô Đơn",
			category: "Sách Bán Chạy",
			image: "/img/17.jpg",
			price: 71000,
			countInStock: 10,
			brand: "NXB Việt Nam",
			rating: 0,
			numReviews: 0,
			description:
				"Đời Có Mấy Tý, Sao Phải Nghĩ (Tái Bản 2022) Nhà Văn Cục Súc được biết tới là một blogger sở hữu những bài post nghìn like cùng nhiều câu nói hot trend có phần cục súc, hài hước và thú vị được đăng tải trên fanpage cùng tên với hơn 1 triệu lượt theo dõi. Lấy phong cách hài “mặn” làm chủ đạo, nội dung của Nhà Văn Cục Súc chủ yếu hướng đến giới trẻ và những sự kiện nổi bật thu hút sự quan tâm lớn từ cộng đồng mạng. “Lá cây cần quang hợp còn mình thì cần quan tâm” Cuộc sống mà, lúc nào cũng đầy rẫy những chuyện phức tạp không ngờ đến. Một vấn đề tưởng như nhỏ xíu cũng có thể khiến bạn trở nên quạu cọ, cục súc.",
		},
		{
			name: "Sài Gòn Thành Phố Tôi Yêu (Tái bản)",
			category: "Sách Bán Chạy",
			image: "/img/11.jpg",
			price: 87000,
			countInStock: 20,
			brand: "NXB Hồng Đức",
			rating: 0,
			numReviews: 0,
			description:
				"'Tập hợp những bài đoạt giải và tiêu biểu từ cuộc thi viết 'Thành Phố Tôi Yêu' do báo Thanh Niên tổ chức (2019-2020)",
		},
		{
			name: "Việt Ma Tân Lục- Quyển 1",
			category: "Sách Bán Chạy",
			image: "/img/2.jpg",
			price: 120000,
			countInStock: 20,
			brand: "NXB Dân Trí",
			rating: 0,
			numReviews: 0,
			description:
				"Việt Ma Tân Lục \n Dòng họ Trịnh cứ 18 năm lại có một người con gái treo cổ. \n Nhưng, một năm trở lại đây, liên tiếp những cái chết bất đắc kỳ tử – không kể nam nữ, không tính trẻ già, chỉ biết, đều là những cái chết thảm khốc! \n Ngay cả những thầy tà, pháp lực nổi tiếng một vùng, cũng không sống sót nổi sau một đêm trú lại nơi này. \n Điều gì đã xảy ra ở ngôi nhà ma ám này? Là hệ lụy của hàng trăm năm oán khí? Hay, oan hồn người con dâu treo cổ ngay trong đêm tân hôn quấy phá? Tất cả đều chưa rõ, chỉ biết, người sống vẫn cứ hoảng loạn, còn những người đã chết thì cứ mãi không siêu thoát, vất vưởng gieo tang tóc.\n Lan Phương – người con gái dị biệt, bị xa lánh trong nhà trưởng tộc họ Trịnh vẫn thường nhìn thấy những hồn ma u tịch. Nhưng, không ai tin cô, cho đến khi Gia Huy – hậu duệ của một gia đình có truyền thống bắt ma – xuất hiện. \nHọ rơi vào vòng xoáy của những oan hồn oán nghiệp tới đòi nợ. Cả hai phải làm gì để cứu chính mình và giúp gia tộc họ Trịnh thoát khỏi kiếp nạn này, cũng như siêu sinh cho các oan hồn? Bí mật gì ẩn giấu đằng sau những cái chết bi thảm \nTác giả: \n Nhóm 4.0 là dự án sáng tác văn học theo mô hình nhóm đầu tiên tại Việt Nam. Lần đầu tiên trong nền xuất bản Việt Nam xuất hiện một “dây chuyền” sáng tác chuyên nghiệp: Thay vì làm việc đơn lẻ theo cảm hứng, các tác giả cùng phối hợp sáng tác theo từng dự án và kế hoạch cụ thể, hướng tới việc hình thành một thói quen sáng tác mới, tạo nên một thế hệ tác giả chuyên nghiệp, sáng tạo ra những tác phẩm có chất lượng và phù hợp với thị hiếu của độc giả\nCác tác phẩm nổi bật của nhóm: Kết giới; Không thể chạm vào em; Đóa hoa anh đào năm ấy; Cái chết ảo; Bên kia giấc mơ; - ... \n Việt Ma Tân Lục là sản phẩm kết hợp của sáu thành viên trong Nhóm 4.0. Ngay từ khi ra mắt, tác phẩm đã nhận được rất nhiều phản hồi tích cực của độc giả, dù là ở phiên bản ebook hay audio, là một trong những tác phẩm tiên phong mở đầu cho trào lưu tiểu thuyết linh dị tại Việt Nam\n",
		},
		{
			name: "Việt Ma Tân Lục- Quyển 2",
			category: "Sách Bán Chạy",
			image: "/img/3.jpg",
			price: 125000,
			countInStock: 20,
			brand: "NXB Dân Trí",
			rating: 0,
			numReviews: 0,
			description:
				"Việt Ma Tân Lục: \n Dòng họ Trịnh cứ 18 năm lại có một người con gái treo cổ. \n Nhưng, một năm trở lại đây, liên tiếp những cái chết bất đắc kỳ tử – không kể nam nữ, không tính trẻ già, chỉ biết, đều là những cái chết thảm khốc! \n Ngay cả những thầy tà, pháp lực nổi tiếng một vùng, cũng không sống sót nổi sau một đêm trú lại nơi này. \n Điều gì đã xảy ra ở ngôi nhà ma ám này? Là hệ lụy của hàng trăm năm oán khí? Hay, oan hồn người con dâu treo cổ ngay trong đêm tân hôn quấy phá? Tất cả đều chưa rõ, chỉ biết, người sống vẫn cứ hoảng loạn, còn những người đã chết thì cứ mãi không siêu thoát, vất vưởng gieo tang tóc.\n Lan Phương – người con gái dị biệt, bị xa lánh trong nhà trưởng tộc họ Trịnh vẫn thường nhìn thấy những hồn ma u tịch. Nhưng, không ai tin cô, cho đến khi Gia Huy – hậu duệ của một gia đình có truyền thống bắt ma – xuất hiện. \nHọ rơi vào vòng xoáy của những oan hồn oán nghiệp tới đòi nợ. Cả hai phải làm gì để cứu chính mình và giúp gia tộc họ Trịnh thoát khỏi kiếp nạn này, cũng như siêu sinh cho các oan hồn? Bí mật gì ẩn giấu đằng sau những cái chết bi thảm \nTác giả: \n Nhóm 4.0 là dự án sáng tác văn học theo mô hình nhóm đầu tiên tại Việt Nam. Lần đầu tiên trong nền xuất bản Việt Nam xuất hiện một “dây chuyền” sáng tác chuyên nghiệp: Thay vì làm việc đơn lẻ theo cảm hứng, các tác giả cùng phối hợp sáng tác theo từng dự án và kế hoạch cụ thể, hướng tới việc hình thành một thói quen sáng tác mới, tạo nên một thế hệ tác giả chuyên nghiệp, sáng tạo ra những tác phẩm có chất lượng và phù hợp với thị hiếu của độc giả\nCác tác phẩm nổi bật của nhóm: Kết giới; Không thể chạm vào em; Đóa hoa anh đào năm ấy; Cái chết ảo; Bên kia giấc mơ; - ... \n Việt Ma Tân Lục là sản phẩm kết hợp của sáu thành viên trong Nhóm 4.0. Ngay từ khi ra mắt, tác phẩm đã nhận được rất nhiều phản hồi tích cực của độc giả, dù là ở phiên bản ebook hay audio, là một trong những tác phẩm tiên phong mở đầu cho trào lưu tiểu thuyết linh dị tại Việt Nam\n",
		},
		{
			name: "Spy X Family -Tập 7",
			category: "Sách Bán Chạy",
			image: "/img/28.jpg",
			price: 35000,
			countInStock: 50,
			brand: "NXB Kim Đồng",
			rating: 0,
			numReviews: 0,
			description:
				"Cuối cùng thì Twilight cũng tiếp xúc được với mục tiêu Desmond lần đầu tiên bằng cách xen vào cuộc gặp gỡ giữa hắn và cậu con trai thứ Damian!! Liệu thông qua cuộc trò chuyện, Twilight có tìm ra được bản chất của mục tiêu không thể dò xét tâm tư này hay không...!?",
		},
		{
			name: "Việt Ma Tân Lục- Quyển 3",
			category: "Sách Bán Chạy",
			image: "/img/10.jpg",
			price: 126000,
			countInStock: 20,
			brand: "NXB Dân Trí",
			rating: 0,
			numReviews: 0,
			description:
				"Việt Ma Tân Lục: \n Dòng họ Trịnh cứ 18 năm lại có một người con gái treo cổ. \n Nhưng, một năm trở lại đây, liên tiếp những cái chết bất đắc kỳ tử – không kể nam nữ, không tính trẻ già, chỉ biết, đều là những cái chết thảm khốc! \n Ngay cả những thầy tà, pháp lực nổi tiếng một vùng, cũng không sống sót nổi sau một đêm trú lại nơi này. \n Điều gì đã xảy ra ở ngôi nhà ma ám này? Là hệ lụy của hàng trăm năm oán khí? Hay, oan hồn người con dâu treo cổ ngay trong đêm tân hôn quấy phá? Tất cả đều chưa rõ, chỉ biết, người sống vẫn cứ hoảng loạn, còn những người đã chết thì cứ mãi không siêu thoát, vất vưởng gieo tang tóc.\n Lan Phương – người con gái dị biệt, bị xa lánh trong nhà trưởng tộc họ Trịnh vẫn thường nhìn thấy những hồn ma u tịch. Nhưng, không ai tin cô, cho đến khi Gia Huy – hậu duệ của một gia đình có truyền thống bắt ma – xuất hiện. \nHọ rơi vào vòng xoáy của những oan hồn oán nghiệp tới đòi nợ. Cả hai phải làm gì để cứu chính mình và giúp gia tộc họ Trịnh thoát khỏi kiếp nạn này, cũng như siêu sinh cho các oan hồn? Bí mật gì ẩn giấu đằng sau những cái chết bi thảm \nTác giả: \n Nhóm 4.0 là dự án sáng tác văn học theo mô hình nhóm đầu tiên tại Việt Nam. Lần đầu tiên trong nền xuất bản Việt Nam xuất hiện một “dây chuyền” sáng tác chuyên nghiệp: Thay vì làm việc đơn lẻ theo cảm hứng, các tác giả cùng phối hợp sáng tác theo từng dự án và kế hoạch cụ thể, hướng tới việc hình thành một thói quen sáng tác mới, tạo nên một thế hệ tác giả chuyên nghiệp, sáng tạo ra những tác phẩm có chất lượng và phù hợp với thị hiếu của độc giả\nCác tác phẩm nổi bật của nhóm: Kết giới; Không thể chạm vào em; Đóa hoa anh đào năm ấy; Cái chết ảo; Bên kia giấc mơ; - ... \n Việt Ma Tân Lục là sản phẩm kết hợp của sáu thành viên trong Nhóm 4.0. Ngay từ khi ra mắt, tác phẩm đã nhận được rất nhiều phản hồi tích cực của độc giả, dù là ở phiên bản ebook hay audio, là một trong những tác phẩm tiên phong mở đầu cho trào lưu tiểu thuyết linh dị tại Việt Nam\n",
		},
		{
			name: "Việt Ma Tân Lục - Quyển 1",
			category: "Văn Học",
			image: "/img/2.jpg",
			price: 120000,
			countInStock: 20,
			brand: "NXB Dân Trí",
			rating: 0,
			numReviews: 0,
			description:
				"Việt Ma Tân Lục \n Dòng họ Trịnh cứ 18 năm lại có một người con gái treo cổ. \n Nhưng, một năm trở lại đây, liên tiếp những cái chết bất đắc kỳ tử – không kể nam nữ, không tính trẻ già, chỉ biết, đều là những cái chết thảm khốc! \n Ngay cả những thầy tà, pháp lực nổi tiếng một vùng, cũng không sống sót nổi sau một đêm trú lại nơi này. \n Điều gì đã xảy ra ở ngôi nhà ma ám này? Là hệ lụy của hàng trăm năm oán khí? Hay, oan hồn người con dâu treo cổ ngay trong đêm tân hôn quấy phá? Tất cả đều chưa rõ, chỉ biết, người sống vẫn cứ hoảng loạn, còn những người đã chết thì cứ mãi không siêu thoát, vất vưởng gieo tang tóc.\n Lan Phương – người con gái dị biệt, bị xa lánh trong nhà trưởng tộc họ Trịnh vẫn thường nhìn thấy những hồn ma u tịch. Nhưng, không ai tin cô, cho đến khi Gia Huy – hậu duệ của một gia đình có truyền thống bắt ma – xuất hiện. \nHọ rơi vào vòng xoáy của những oan hồn oán nghiệp tới đòi nợ. Cả hai phải làm gì để cứu chính mình và giúp gia tộc họ Trịnh thoát khỏi kiếp nạn này, cũng như siêu sinh cho các oan hồn? Bí mật gì ẩn giấu đằng sau những cái chết bi thảm \nTác giả: \n Nhóm 4.0 là dự án sáng tác văn học theo mô hình nhóm đầu tiên tại Việt Nam. Lần đầu tiên trong nền xuất bản Việt Nam xuất hiện một “dây chuyền” sáng tác chuyên nghiệp: Thay vì làm việc đơn lẻ theo cảm hứng, các tác giả cùng phối hợp sáng tác theo từng dự án và kế hoạch cụ thể, hướng tới việc hình thành một thói quen sáng tác mới, tạo nên một thế hệ tác giả chuyên nghiệp, sáng tạo ra những tác phẩm có chất lượng và phù hợp với thị hiếu của độc giả\nCác tác phẩm nổi bật của nhóm: Kết giới; Không thể chạm vào em; Đóa hoa anh đào năm ấy; Cái chết ảo; Bên kia giấc mơ; - ... \n Việt Ma Tân Lục là sản phẩm kết hợp của sáu thành viên trong Nhóm 4.0. Ngay từ khi ra mắt, tác phẩm đã nhận được rất nhiều phản hồi tích cực của độc giả, dù là ở phiên bản ebook hay audio, là một trong những tác phẩm tiên phong mở đầu cho trào lưu tiểu thuyết linh dị tại Việt Nam\n",
		},
		{
			name: "Việt Ma Tân Lục - Quyển 2",
			category: "Văn Học",
			image: "/img/3.jpg",
			price: 125000,
			countInStock: 20,
			brand: "NXB Dân Trí",
			rating: 0,
			numReviews: 0,
			description:
				"Việt Ma Tân Lục: \n Dòng họ Trịnh cứ 18 năm lại có một người con gái treo cổ. \n Nhưng, một năm trở lại đây, liên tiếp những cái chết bất đắc kỳ tử – không kể nam nữ, không tính trẻ già, chỉ biết, đều là những cái chết thảm khốc! \n Ngay cả những thầy tà, pháp lực nổi tiếng một vùng, cũng không sống sót nổi sau một đêm trú lại nơi này. \n Điều gì đã xảy ra ở ngôi nhà ma ám này? Là hệ lụy của hàng trăm năm oán khí? Hay, oan hồn người con dâu treo cổ ngay trong đêm tân hôn quấy phá? Tất cả đều chưa rõ, chỉ biết, người sống vẫn cứ hoảng loạn, còn những người đã chết thì cứ mãi không siêu thoát, vất vưởng gieo tang tóc.\n Lan Phương – người con gái dị biệt, bị xa lánh trong nhà trưởng tộc họ Trịnh vẫn thường nhìn thấy những hồn ma u tịch. Nhưng, không ai tin cô, cho đến khi Gia Huy – hậu duệ của một gia đình có truyền thống bắt ma – xuất hiện. \nHọ rơi vào vòng xoáy của những oan hồn oán nghiệp tới đòi nợ. Cả hai phải làm gì để cứu chính mình và giúp gia tộc họ Trịnh thoát khỏi kiếp nạn này, cũng như siêu sinh cho các oan hồn? Bí mật gì ẩn giấu đằng sau những cái chết bi thảm \nTác giả: \n Nhóm 4.0 là dự án sáng tác văn học theo mô hình nhóm đầu tiên tại Việt Nam. Lần đầu tiên trong nền xuất bản Việt Nam xuất hiện một “dây chuyền” sáng tác chuyên nghiệp: Thay vì làm việc đơn lẻ theo cảm hứng, các tác giả cùng phối hợp sáng tác theo từng dự án và kế hoạch cụ thể, hướng tới việc hình thành một thói quen sáng tác mới, tạo nên một thế hệ tác giả chuyên nghiệp, sáng tạo ra những tác phẩm có chất lượng và phù hợp với thị hiếu của độc giả\nCác tác phẩm nổi bật của nhóm: Kết giới; Không thể chạm vào em; Đóa hoa anh đào năm ấy; Cái chết ảo; Bên kia giấc mơ; - ... \n Việt Ma Tân Lục là sản phẩm kết hợp của sáu thành viên trong Nhóm 4.0. Ngay từ khi ra mắt, tác phẩm đã nhận được rất nhiều phản hồi tích cực của độc giả, dù là ở phiên bản ebook hay audio, là một trong những tác phẩm tiên phong mở đầu cho trào lưu tiểu thuyết linh dị tại Việt Nam\n",
		},
		{
			name: "Việt Ma Tân Lục - Quyển 3",
			category: "Văn Học",
			image: "/img/10.jpg",
			price: 126000,
			countInStock: 20,
			brand: "NXB Dân Trí",
			rating: 0,
			numReviews: 0,
			description:
				"Việt Ma Tân Lục: \n Dòng họ Trịnh cứ 18 năm lại có một người con gái treo cổ. \n Nhưng, một năm trở lại đây, liên tiếp những cái chết bất đắc kỳ tử – không kể nam nữ, không tính trẻ già, chỉ biết, đều là những cái chết thảm khốc! \n Ngay cả những thầy tà, pháp lực nổi tiếng một vùng, cũng không sống sót nổi sau một đêm trú lại nơi này. \n Điều gì đã xảy ra ở ngôi nhà ma ám này? Là hệ lụy của hàng trăm năm oán khí? Hay, oan hồn người con dâu treo cổ ngay trong đêm tân hôn quấy phá? Tất cả đều chưa rõ, chỉ biết, người sống vẫn cứ hoảng loạn, còn những người đã chết thì cứ mãi không siêu thoát, vất vưởng gieo tang tóc.\n Lan Phương – người con gái dị biệt, bị xa lánh trong nhà trưởng tộc họ Trịnh vẫn thường nhìn thấy những hồn ma u tịch. Nhưng, không ai tin cô, cho đến khi Gia Huy – hậu duệ của một gia đình có truyền thống bắt ma – xuất hiện. \nHọ rơi vào vòng xoáy của những oan hồn oán nghiệp tới đòi nợ. Cả hai phải làm gì để cứu chính mình và giúp gia tộc họ Trịnh thoát khỏi kiếp nạn này, cũng như siêu sinh cho các oan hồn? Bí mật gì ẩn giấu đằng sau những cái chết bi thảm \nTác giả: \n Nhóm 4.0 là dự án sáng tác văn học theo mô hình nhóm đầu tiên tại Việt Nam. Lần đầu tiên trong nền xuất bản Việt Nam xuất hiện một “dây chuyền” sáng tác chuyên nghiệp: Thay vì làm việc đơn lẻ theo cảm hứng, các tác giả cùng phối hợp sáng tác theo từng dự án và kế hoạch cụ thể, hướng tới việc hình thành một thói quen sáng tác mới, tạo nên một thế hệ tác giả chuyên nghiệp, sáng tạo ra những tác phẩm có chất lượng và phù hợp với thị hiếu của độc giả\nCác tác phẩm nổi bật của nhóm: Kết giới; Không thể chạm vào em; Đóa hoa anh đào năm ấy; Cái chết ảo; Bên kia giấc mơ; - ... \n Việt Ma Tân Lục là sản phẩm kết hợp của sáu thành viên trong Nhóm 4.0. Ngay từ khi ra mắt, tác phẩm đã nhận được rất nhiều phản hồi tích cực của độc giả, dù là ở phiên bản ebook hay audio, là một trong những tác phẩm tiên phong mở đầu cho trào lưu tiểu thuyết linh dị tại Việt Nam\n",
		},
		{
			name: "Sài Gòn Thành Phố Tôi Yêu",
			category: "Văn Học",
			image: "/img/11.jpg",
			price: 87000,
			countInStock: 20,
			brand: "NXB Hồng Đức",
			rating: 0,
			numReviews: 0,
			description:
				"'Tập hợp những bài đoạt giải và tiêu biểu từ cuộc thi viết 'Thành Phố Tôi Yêu' do báo Thanh Niên tổ chức (2019-2020)",
		},
		{
			name: "Thương Nhớ Miền Trung",
			category: "Văn Học",
			image: "/img/12.jpg",
			price: 90000,
			countInStock: 20,
			brand: "NXB Hồng Đức",
			rating: 0,
			numReviews: 0,
			description:
				"NHỮNG BÀI ĐOẠT GIẢI VÀ TIÊU BIỂU TỪ CUỘC THI VIẾT “THƯƠNG NHỚ MIỀN TRUNG” CỦA BÁO THANH NIÊN 2020",
		},
		{
			name: "Sách Giáo Khoa Bộ Lớp 4 - Sách Bài Học (Bộ 9 Cuốn)",
			category: "Sách Giáo Khoa",
			image: "/img/4.jpg",
			price: 102000,
			countInStock: 20,
			brand: "NXB Đại Học Sư Phạm TPHCM",
			rating: 0,
			numReviews: 0,
			description:
				"Sách Giáo Khoa Bộ Lớp 4 - Sách Bài Học (Bộ 9 Cuốn) (2022) + Bao Sách Nylon TP Bao Gồm:	- Cuộn Bao Sách Nylon TP (10 Tờ/Cuộn) - Sách Giáo Khoa Bộ Lớp 4 - Sách Bài Học (Bộ 9 Cuốn) (2022)",
		},
		{
			name: "Trọng Tâm Ngữ Pháp Tiếng Anh Lớp 4 - Tập 2",
			category: "Sách Tham Khảo",
			image: "/img/5.jpg",
			price: 66300,
			countInStock: 20,
			brand: "NXB Đại Học Quốc Gia Hà Nội",
			rating: 0,
			numReviews: 0,
			description:
				"Nhằm giúp giáo viên và các em học sinh có thêm tài liệu luyện tập, củng cố, mở rộng và nâng cao kiến thức, chúng tôi biên soạn bộ sách Trọng tâm ngữ pháp Tiếng Anh lớp 4. Bộ sách gồm hai tập:Trọng tâm ngữ pháp Tiếng Anh 4 tập 1: Unit 1 – Unit 10	Trọng tâm ngữ pháp Tiếng Anh 4 tập 2: Unit 11 – Unit 20			Mỗi Unit gồm hai bài kiểm tra. Bài tập được biên soạn đa dạng, phong phú, bám sát chương trình và sách giáo khoa, trình bày khoa học, dễ hiểu. Kết hợp với nội dung trong sách là link tải đĩa CD (đính kèm trên bìa sách) phát âm chuẩn tiếng Anh của người bản ngữ. Các em có thể sử dụng điện thoại smartphone để quét mã QR và tải các bài học một cách nhanh chóng và thuận tiện. Chúng tôi hy vọng bộ sách sẽ là tài liệu hữu ích cho các em học sinh, các thầy cô giáo và các vị phụ huynh trong việc tự học và ôn luyện tiếng Anh một cách hiệu quả.",
		},
		{
			name: "Trọng Tâm Ngữ Pháp Tiếng Anh Lớp 4 - Tập 1",
			category: "Sách Tham Khảo",
			image: "/img/6.jpg",
			price: 66300,
			countInStock: 20,
			brand: "NXB Đại Học Quốc Gia Hà Nội",
			rating: 0,
			numReviews: 0,
			description:
				"Nhằm giúp giáo viên và các em học sinh có thêm tài liệu luyện tập, củng cố, mở rộng và nâng cao kiến thức, chúng tôi biên soạn bộ sách Trọng tâm ngữ pháp Tiếng Anh lớp 4. Bộ sách gồm hai tập:Trọng tâm ngữ pháp Tiếng Anh 4 tập 1: Unit 1 – Unit 10	Trọng tâm ngữ pháp Tiếng Anh 4 tập 2: Unit 11 – Unit 20			Mỗi Unit gồm hai bài kiểm tra. Bài tập được biên soạn đa dạng, phong phú, bám sát chương trình và sách giáo khoa, trình bày khoa học, dễ hiểu. Kết hợp với nội dung trong sách là link tải đĩa CD (đính kèm trên bìa sách) phát âm chuẩn tiếng Anh của người bản ngữ. Các em có thể sử dụng điện thoại smartphone để quét mã QR và tải các bài học một cách nhanh chóng và thuận tiện. Chúng tôi hy vọng bộ sách sẽ là tài liệu hữu ích cho các em học sinh, các thầy cô giáo và các vị phụ huynh trong việc tự học và ôn luyện tiếng Anh một cách hiệu quả.",
		},
		{
			name: "Luyện Thi Vào Lớp 10 - Môn Ngữ Văn",
			category: "Sách Tham Khảo",
			image: "/img/7.jpg",
			price: 75500,
			countInStock: 20,
			brand: "NXB Hải Phòng",
			rating: 0,
			numReviews: 0,
			description:
				"Môn ngữ văn là một trong những môn chính thi vào lớp 10 cho học sinh tất cả các tỉnh thành trên cả nước. Vì vậy, cuốn ô Luyện Thi Vào Lớp 10 - Môn Ngữ Văngiúp các em cũng như thầy cô có trong tay những tư liệu kiến thức cần thiết để dạy và học. Sách được biên soạn bám sát theo chương trình sách giáo khoa Ngữ Văn 9. Bố cục gồm 4 phần: - Phần 1: Nghị luận văn học ( kiến thức cơ bản và luyện đề tùng tác phẩm văn học) - Phần 2: Nghị luận xã hội (43 bài văn nghị luận xã hội hoàn chỉnh)	- Phần 3: Tổng hợp kiến thức Tiếng Việt	- Phần 4: Các đề thi tham khảo.",
		},
		{
			name: "207 Đề Và Bài Văn Văn Hay Lớp 2",
			category: "Sách Tham Khảo",
			image: "/img/8.jpg",
			price: 28000,
			countInStock: 20,
			brand: "NXB Đại Học Sư Phạm",
			rating: 0,
			numReviews: 0,
			description:
				"Môn ngữ văn là một trong những môn chính thi vào lớp 10 cho học sinh tất cả các tỉnh thành trên cả nước. Vì vậy, cuốn ô Luyện Thi Vào Lớp 10 - Môn Ngữ Văngiúp các em cũng như thầy cô có trong tay những tư liệu kiến thức cần thiết để dạy và học. Sách được biên soạn bám sát theo chương trình sách giáo khoa Ngữ Văn 9. Bố cục gồm 4 phần: - Phần 1: Nghị luận văn học ( kiến thức cơ bản và luyện đề tùng tác phẩm văn học) - Phần 2: Nghị luận xã hội (43 bài văn nghị luận xã hội hoàn chỉnh)	- Phần 3: Tổng hợp kiến thức Tiếng Việt	- Phần 4: Các đề thi tham khảo.",
		},
		{
			name: "Tuyển Chọn Bài Văn Hay Chọn Lọc 5",
			category: "Sách Tham Khảo",
			image: "/img/9.jpg",
			price: 25000,
			countInStock: 20,
			brand: "NXB Đại Học Sư Phạm",
			rating: 0,
			numReviews: 0,
			description:
				"Môn ngữ văn là một trong những môn chính thi vào lớp 10 cho học sinh tất cả các tỉnh thành trên cả nước. Vì vậy, cuốn ô Luyện Thi Vào Lớp 10 - Môn Ngữ Văngiúp các em cũng như thầy cô có trong tay những tư liệu kiến thức cần thiết để dạy và học. Sách được biên soạn bám sát theo chương trình sách giáo khoa Ngữ Văn 9. Bố cục gồm 4 phần: - Phần 1: Nghị luận văn học ( kiến thức cơ bản và luyện đề tùng tác phẩm văn học) - Phần 2: Nghị luận xã hội (43 bài văn nghị luận xã hội hoàn chỉnh)	- Phần 3: Tổng hợp kiến thức Tiếng Việt	- Phần 4: Các đề thi tham khảo.",
		},
		{
			name: "Đầu Tư Tài Chính (Tái Bản)",
			category: "Kinh Tế",
			image: "/img/13.jpg",
			price: 659000,
			countInStock: 20,
			brand: "NXB Kinh tế TP.Hồ Chí Minh",
			rating: 0,
			numReviews: 0,
			description:
				"Bạn muốn được tự do, bạn muốn thoải mái trong cuộc sống thường nhật và không phải trả lời bất cứ ai! Bạn khao khát có nhiều thời gian hơn ở bên cạnh những người thân yêu của mình mà vẫn có thu nhập để nuôi sống gia đình! Đầu tư tài chính giúp bạn hoàn thành giấc mơ tự do tài chính đó, nghĩa là bạn không hề có cấp trên, thoái mái đi du lịch và làm việc khắp nơi trên thế giới! Đó là cuộc sống của mộtnhà đầu tư tài chính thành công.",
		},
		{
			name: "Bóc Phốt Tài Chính - Giàu Chậm Nhưng Chắc",
			category: "Kinh Tế",
			image: "/img/14.jpg",
			price: 164000,
			countInStock: 20,
			brand: "NXB Dân Trí",
			rating: 0,
			numReviews: 0,
			description:
				"Bạn muốn được tự do, bạn muốn thoải mái trong cuộc sống thường nhật và không phải trả lời bất cứ ai! Bạn khao khát có nhiều thời gian hơn ở bên cạnh những người thân yêu của mình mà vẫn có thu nhập để nuôi sống gia đình! Đầu tư tài chính giúp bạn hoàn thành giấc mơ tự do tài chính đó, nghĩa là bạn không hề có cấp trên, thoái mái đi du lịch và làm việc khắp nơi trên thế giới! Đó là cuộc sống của mộtnhà đầu tư tài chính thành công.",
		},
		{
			name: "Từ Điển Tiếng “Em” - Tái Bản 2021",
			category: "Truyện Ngắn - Tản Văn",
			image: "/img/15.jpg",
			price: 69000,
			countInStock: 10,
			brand: "NXB Phụ Nữ Việt Nam",
			rating: 0,
			numReviews: 0,
			description:
				"TỪ ĐIỂN TIẾNG “EM” – Định nghĩa về thế giới mới! Bạn sẽ bất ngờ, khi cầm cuốn “từ điển” xinh xinh này trên tay. Và sẽ còn ngạc nhiên hơn nữa, khi bắt đầu đọc từng trang sách… Dĩ nhiên là vì “Từ điển tiếng “Em” không phải là một cuốn từ điển thông thường rồi! Nói đến “từ điển”, xưa nay chúng ta đều nghĩ về một bộ sách đồ sộ, giải thích ý nghĩa, cách dùng, dịch, cách phát âm, và thường kèm theo các ví dụ về cách sử dụng từ đó. Tuy nhiên, với cuốn sách “Từ điển tiếng “em”, các bạn sẽ hết sức bất ngờ với những định nghĩa mới, bắt trend, sáng tạo, thông minh và vô cùng hài hước.",
		},
		{
			name: "Đời Có Mấy Tý, Sao Phải Nghĩ",
			category: "Truyện Ngắn - Tản Văn",
			image: "/img/16.jpg",
			price: 71000,
			countInStock: 10,
			brand: "NXB Việt Nam",
			rating: 0,
			numReviews: 0,
			description:
				"Đời Có Mấy Tý, Sao Phải Nghĩ (Tái Bản 2022) Nhà Văn Cục Súc được biết tới là một blogger sở hữu những bài post nghìn like cùng nhiều câu nói hot trend có phần cục súc, hài hước và thú vị được đăng tải trên fanpage cùng tên với hơn 1 triệu lượt theo dõi. Lấy phong cách hài “mặn” làm chủ đạo, nội dung của Nhà Văn Cục Súc chủ yếu hướng đến giới trẻ và những sự kiện nổi bật thu hút sự quan tâm lớn từ cộng đồng mạng. “Lá cây cần quang hợp còn mình thì cần quan tâm” Cuộc sống mà, lúc nào cũng đầy rẫy những chuyện phức tạp không ngờ đến. Một vấn đề tưởng như nhỏ xíu cũng có thể khiến bạn trở nên quạu cọ, cục súc.",
		},
		{
			name: "Phải Lòng Với Cô Đơn (Tái Bản 2022)",
			category: "Truyện Ngắn - Tản Văn",
			image: "/img/17.jpg",
			price: 71000,
			countInStock: 10,
			brand: "NXB Việt Nam",
			rating: 0,
			numReviews: 0,
			description:
				"Đời Có Mấy Tý, Sao Phải Nghĩ (Tái Bản 2022) Nhà Văn Cục Súc được biết tới là một blogger sở hữu những bài post nghìn like cùng nhiều câu nói hot trend có phần cục súc, hài hước và thú vị được đăng tải trên fanpage cùng tên với hơn 1 triệu lượt theo dõi. Lấy phong cách hài “mặn” làm chủ đạo, nội dung của Nhà Văn Cục Súc chủ yếu hướng đến giới trẻ và những sự kiện nổi bật thu hút sự quan tâm lớn từ cộng đồng mạng. “Lá cây cần quang hợp còn mình thì cần quan tâm” Cuộc sống mà, lúc nào cũng đầy rẫy những chuyện phức tạp không ngờ đến. Một vấn đề tưởng như nhỏ xíu cũng có thể khiến bạn trở nên quạu cọ, cục súc.",
		},
		{
			name: "Ếch Ộp - Tuyển Tập Truyện Siêu Ngắn",
			category: "Truyện Ngắn - Tản Văn",
			image: "/img/18.jpg",
			price: 89000,
			countInStock: 15,
			brand: "NXB Dân Trí",
			rating: 0,
			numReviews: 0,
			description:
				"Hài hước, mặn mà, bắt sóng nhanh chóng các xu hướng được giới trẻ quan tâm  chính là những gì có trong cuốn sách “Ếch ộp – Tuyển tập truyện siêu ngắn”. Từ chuyện FA, yêu đương, chia tay, đến chuyện trong nhà ngoài ngõ, văn hóa mua hàng inbox, tà tưa full topping, ma sói gắn kết tình đồng đội… gi gỉ gì gi cái gì cũng có. Cuộc sống của chúng ta, mỗi ngày có hàng tá những mệt mỏi, muộn phiền bủa vây bạn. Cúi xuống thì thấy hết tiền, ngẩng đầu thì thấy deadline, sếp mắng, người yêu quạu,… Nếu như bạn cứ mãi chìm đắm trong mớ hỗn độn, loay hoang ấy thì tâm trạng càng trở nên tiêu cực hơn thôi. Vậy nên hãy lật giở từng trang sách siêu hài hước, độc nhất vô nhị của chủ fanpage Ếch ộp – Truyện tranh Cực Vip Pro Luxury để thả lỏng, tận hưởng sự vui vẻ, xóa tan đi những xui xẻo, cau có bạn gặp phải",
		},
		{
			name: "Thế Gian Này Dẫu Đẹp Nhưng Cũng Chẳng Bằng Em",
			category: "Truyện Ngắn - Tản Văn",
			image: "/img/19.jpg",
			price: 189000,
			countInStock: 15,
			brand: "NXB Văn Học",
			rating: 0,
			numReviews: 0,
			description:
				"Hài hước, mặn mà, bắt sóng nhanh chóng các xu hướng được giới trẻ quan tâm  chính là những gì có trong cuốn sách “Ếch ộp – Tuyển tập truyện siêu ngắn”. Từ chuyện FA, yêu đương, chia tay, đến chuyện trong nhà ngoài ngõ, văn hóa mua hàng inbox, tà tưa full topping, ma sói gắn kết tình đồng đội… gi gỉ gì gi cái gì cũng có. Cuộc sống của chúng ta, mỗi ngày có hàng tá những mệt mỏi, muộn phiền bủa vây bạn. Cúi xuống thì thấy hết tiền, ngẩng đầu thì thấy deadline, sếp mắng, người yêu quạu,… Nếu như bạn cứ mãi chìm đắm trong mớ hỗn độn, loay hoang ấy thì tâm trạng càng trở nên tiêu cực hơn thôi. Vậy nên hãy lật giở từng trang sách siêu hài hước, độc nhất vô nhị của chủ fanpage Ếch ộp – Truyện tranh Cực Vip Pro Luxury để thả lỏng, tận hưởng sự vui vẻ, xóa tan đi những xui xẻo, cau có bạn gặp phải",
		},
		{
			name: "Miền Đông",
			category: "Truyện Ngắn - Tản Văn",
			image: "/img/20.jpg",
			price: 200000,
			countInStock: 15,
			brand: "NXB Văn Học",
			rating: 0,
			numReviews: 0,
			description:
				"MIỀN ĐÔNG – Tập truyện ngắn chọn lọc của 3 tác giả họ Nguyễn cùng ở miền Đông: NGUYỄN MỘT, NGUYỄN TRÍ và NGUYỄN HIỆP. Mỗi tác giả góp mặt bằng 9 truyện ngắn đặc sắc với phong cách đặc trưng của riêng mình tạo thành “bản hòa tấu 27 chương” - vừa có sự hòa điệu, vừa thể hiện âm sắc độc đáo riêng của từng nhạc cụ. Truyện ngắn của Nguyễn Một thường có giọng điệu phóng khoáng và ẩn chứa tư duy thâm trầm, sâu sắc của nhà văn về những vấn đề nhân sinh. Ông thường khắc họa về mối quan hệ giữa sự sống và cái chết; khắc họa mối quan hệ gắn bó giữa tâm hồn con người và những dòng sông, các miền đất ông đã từng sinh sống. Cái nhìn của nhà văn hướng về sự đa chiều kích trong nội tâm, tính cách nhân vật. Thế giới nhân vật của Nguyễn Một thường có sự giằng xé, mâu thuẫn giữa thiện và ác, cái tầm thường và cái thiêng liêng, cao cả. Truyện ngắn của Nguyễn Trí thấm đẫm chất đời, chất bụi bặm và ẩn chứa chất “muối” của đời sống qua những chi tiết ngổn ngang, bề bộn. Ông thường khắc họa tính cách nhân vật thông qua biểu hiện của hành động, lời nói mà ít miêu tả diễn biến tâm trạng, nội tâm. Người đọc văn của Nguyễn Trí như được sống, trải nghiệm cùng thế giới nhân vật mà ông miêu tả. Theo tôi, Nguyễn Trí là nhà văn của những kiếp người lầm lạc nhưng vẫn giữ trong tâm hồn vẻ đẹp của lương tri và khát vọng sống.",
		},
		{
			name: "Bức Thư Của Người Đàn Bà Không Quen",
			category: "Truyện Ngắn - Tản Văn",
			image: "/img/21.jpg",
			price: 210000,
			countInStock: 15,
			brand: "NXB Văn Học",
			rating: 0,
			numReviews: 0,
			description:
				"MIỀN ĐÔNG – Tập truyện ngắn chọn lọc của 3 tác giả họ Nguyễn cùng ở miền Đông: NGUYỄN MỘT, NGUYỄN TRÍ và NGUYỄN HIỆP. Mỗi tác giả góp mặt bằng 9 truyện ngắn đặc sắc với phong cách đặc trưng của riêng mình tạo thành “bản hòa tấu 27 chương” - vừa có sự hòa điệu, vừa thể hiện âm sắc độc đáo riêng của từng nhạc cụ. Truyện ngắn của Nguyễn Một thường có giọng điệu phóng khoáng và ẩn chứa tư duy thâm trầm, sâu sắc của nhà văn về những vấn đề nhân sinh. Ông thường khắc họa về mối quan hệ giữa sự sống và cái chết; khắc họa mối quan hệ gắn bó giữa tâm hồn con người và những dòng sông, các miền đất ông đã từng sinh sống. Cái nhìn của nhà văn hướng về sự đa chiều kích trong nội tâm, tính cách nhân vật. Thế giới nhân vật của Nguyễn Một thường có sự giằng xé, mâu thuẫn giữa thiện và ác, cái tầm thường và cái thiêng liêng, cao cả. Truyện ngắn của Nguyễn Trí thấm đẫm chất đời, chất bụi bặm và ẩn chứa chất “muối” của đời sống qua những chi tiết ngổn ngang, bề bộn. Ông thường khắc họa tính cách nhân vật thông qua biểu hiện của hành động, lời nói mà ít miêu tả diễn biến tâm trạng, nội tâm. Người đọc văn của Nguyễn Trí như được sống, trải nghiệm cùng thế giới nhân vật mà ông miêu tả. Theo tôi, Nguyễn Trí là nhà văn của những kiếp người lầm lạc nhưng vẫn giữ trong tâm hồn vẻ đẹp của lương tri và khát vọng sống.",
		},
		{
			name: "Có Một Ngày, Bố Mẹ Sẽ Già Đi",
			category: "Truyện Ngắn - Tản Văn",
			image: "/img/22.jpg",
			price: 100000,
			countInStock: 12,
			brand: "NXB Văn Học",
			rating: 0,
			numReviews: 0,
			description:
				"Có Một Ngày, Bố Mẹ Sẽ Già Đi – Tập truyện ngắn chọn lọc của 3 tác giả họ Nguyễn cùng ở miền Đông: NGUYỄN MỘT, NGUYỄN TRÍ và NGUYỄN HIỆP. Mỗi tác giả góp mặt bằng 9 truyện ngắn đặc sắc với phong cách đặc trưng của riêng mình tạo thành “bản hòa tấu 27 chương” - vừa có sự hòa điệu, vừa thể hiện âm sắc độc đáo riêng của từng nhạc cụ. Truyện ngắn của Nguyễn Một thường có giọng điệu phóng khoáng và ẩn chứa tư duy thâm trầm, sâu sắc của nhà văn về những vấn đề nhân sinh. Ông thường khắc họa về mối quan hệ giữa sự sống và cái chết; khắc họa mối quan hệ gắn bó giữa tâm hồn con người và những dòng sông, các miền đất ông đã từng sinh sống. Cái nhìn của nhà văn hướng về sự đa chiều kích trong nội tâm, tính cách nhân vật. Thế giới nhân vật của Nguyễn Một thường có sự giằng xé, mâu thuẫn giữa thiện và ác, cái tầm thường và cái thiêng liêng, cao cả. Truyện ngắn của Nguyễn Trí thấm đẫm chất đời, chất bụi bặm và ẩn chứa chất “muối” của đời sống qua những chi tiết ngổn ngang, bề bộn. Ông thường khắc họa tính cách nhân vật thông qua biểu hiện của hành động, lời nói mà ít miêu tả diễn biến tâm trạng, nội tâm. Người đọc văn của Nguyễn Trí như được sống, trải nghiệm cùng thế giới nhân vật mà ông miêu tả. Theo tôi, Nguyễn Trí là nhà văn của những kiếp người lầm lạc nhưng vẫn giữ trong tâm hồn vẻ đẹp của lương tri và khát vọng sống.",
		},
		{
			name: "Combo Hành Trình 10 Năm",
			category: "Truyện Ngắn - Tản Văn",
			image: "/img/23.png",
			price: 386000,
			countInStock: 10,
			brand: "NXB Văn Học",
			rating: 0,
			numReviews: 0,
			description:
				"Combo Hành Trình 10 Năm - Hành Trình Từ Cô Đơn Đến Hạnh Phúc – Tập truyện ngắn chọn lọc của 3 tác giả họ Nguyễn cùng ở miền Đông: NGUYỄN MỘT, NGUYỄN TRÍ và NGUYỄN HIỆP. Mỗi tác giả góp mặt bằng 9 truyện ngắn đặc sắc với phong cách đặc trưng của riêng mình tạo thành “bản hòa tấu 27 chương” - vừa có sự hòa điệu, vừa thể hiện âm sắc độc đáo riêng của từng nhạc cụ. Truyện ngắn của Nguyễn Một thường có giọng điệu phóng khoáng và ẩn chứa tư duy thâm trầm, sâu sắc của nhà văn về những vấn đề nhân sinh. Ông thường khắc họa về mối quan hệ giữa sự sống và cái chết; khắc họa mối quan hệ gắn bó giữa tâm hồn con người và những dòng sông, các miền đất ông đã từng sinh sống. Cái nhìn của nhà văn hướng về sự đa chiều kích trong nội tâm, tính cách nhân vật. Thế giới nhân vật của Nguyễn Một thường có sự giằng xé, mâu thuẫn giữa thiện và ác, cái tầm thường và cái thiêng liêng, cao cả. Truyện ngắn của Nguyễn Trí thấm đẫm chất đời, chất bụi bặm và ẩn chứa chất “muối” của đời sống qua những chi tiết ngổn ngang, bề bộn. Ông thường khắc họa tính cách nhân vật thông qua biểu hiện của hành động, lời nói mà ít miêu tả diễn biến tâm trạng, nội tâm. Người đọc văn của Nguyễn Trí như được sống, trải nghiệm cùng thế giới nhân vật mà ông miêu tả. Theo tôi, Nguyễn Trí là nhà văn của những kiếp người lầm lạc nhưng vẫn giữ trong tâm hồn vẻ đẹp của lương tri và khát vọng sống.",
		},
		{
			name: "BoxSet Dạy Con Làm Giàu - Trọn Bộ 13 Tập",
			category: "Kinh Tế",
			image: "/img/24.jpg",
			price: 1200000,
			countInStock: 10,
			brand: "NXB Văn Học",
			rating: 0,
			numReviews: 0,
			description:
				"BoxSet Dạy Con Làm Giàu - Trọn Bộ 13 Tập – Tập truyện ngắn chọn lọc của 3 tác giả họ Nguyễn cùng ở miền Đông: NGUYỄN MỘT, NGUYỄN TRÍ và NGUYỄN HIỆP. Mỗi tác giả góp mặt bằng 9 truyện ngắn đặc sắc với phong cách đặc trưng của riêng mình tạo thành “bản hòa tấu 27 chương” - vừa có sự hòa điệu, vừa thể hiện âm sắc độc đáo riêng của từng nhạc cụ. Truyện ngắn của Nguyễn Một thường có giọng điệu phóng khoáng và ẩn chứa tư duy thâm trầm, sâu sắc của nhà văn về những vấn đề nhân sinh. Ông thường khắc họa về mối quan hệ giữa sự sống và cái chết; khắc họa mối quan hệ gắn bó giữa tâm hồn con người và những dòng sông, các miền đất ông đã từng sinh sống. Cái nhìn của nhà văn hướng về sự đa chiều kích trong nội tâm, tính cách nhân vật. Thế giới nhân vật của Nguyễn Một thường có sự giằng xé, mâu thuẫn giữa thiện và ác, cái tầm thường và cái thiêng liêng, cao cả. Truyện ngắn của Nguyễn Trí thấm đẫm chất đời, chất bụi bặm và ẩn chứa chất “muối” của đời sống qua những chi tiết ngổn ngang, bề bộn. Ông thường khắc họa tính cách nhân vật thông qua biểu hiện của hành động, lời nói mà ít miêu tả diễn biến tâm trạng, nội tâm. Người đọc văn của Nguyễn Trí như được sống, trải nghiệm cùng thế giới nhân vật mà ông miêu tả. Theo tôi, Nguyễn Trí là nhà văn của những kiếp người lầm lạc nhưng vẫn giữ trong tâm hồn vẻ đẹp của lương tri và khát vọng sống.",
		},
		{
			name: "How Money Works - Hiểu Hết Về Tiền",
			category: "Kinh Tế",
			image: "/img/25.jpg",
			price: 300000,
			countInStock: 10,
			brand: "NXB Văn Học",
			rating: 0,
			numReviews: 0,
			description:
				"How Money Works - Hiểu Hết Về Tiền – Tập truyện ngắn chọn lọc của 3 tác giả họ Nguyễn cùng ở miền Đông: NGUYỄN MỘT, NGUYỄN TRÍ và NGUYỄN HIỆP. Mỗi tác giả góp mặt bằng 9 truyện ngắn đặc sắc với phong cách đặc trưng của riêng mình tạo thành “bản hòa tấu 27 chương” - vừa có sự hòa điệu, vừa thể hiện âm sắc độc đáo riêng của từng nhạc cụ. Truyện ngắn của Nguyễn Một thường có giọng điệu phóng khoáng và ẩn chứa tư duy thâm trầm, sâu sắc của nhà văn về những vấn đề nhân sinh. Ông thường khắc họa về mối quan hệ giữa sự sống và cái chết; khắc họa mối quan hệ gắn bó giữa tâm hồn con người và những dòng sông, các miền đất ông đã từng sinh sống. Cái nhìn của nhà văn hướng về sự đa chiều kích trong nội tâm, tính cách nhân vật. Thế giới nhân vật của Nguyễn Một thường có sự giằng xé, mâu thuẫn giữa thiện và ác, cái tầm thường và cái thiêng liêng, cao cả. Truyện ngắn của Nguyễn Trí thấm đẫm chất đời, chất bụi bặm và ẩn chứa chất “muối” của đời sống qua những chi tiết ngổn ngang, bề bộn. Ông thường khắc họa tính cách nhân vật thông qua biểu hiện của hành động, lời nói mà ít miêu tả diễn biến tâm trạng, nội tâm. Người đọc văn của Nguyễn Trí như được sống, trải nghiệm cùng thế giới nhân vật mà ông miêu tả. Theo tôi, Nguyễn Trí là nhà văn của những kiếp người lầm lạc nhưng vẫn giữ trong tâm hồn vẻ đẹp của lương tri và khát vọng sống.",
		},
		{
			name: "Tiền Quả Thật Phiền",
			category: "Kinh Tế",
			image: "/img/26.jpg",
			price: 200000,
			countInStock: 10,
			brand: "NXB Văn Học",
			rating: 0,
			numReviews: 0,
			description:
				"Tiền Quả Thật Phiền – Tập truyện ngắn chọn lọc của 3 tác giả họ Nguyễn cùng ở miền Đông: NGUYỄN MỘT, NGUYỄN TRÍ và NGUYỄN HIỆP. Mỗi tác giả góp mặt bằng 9 truyện ngắn đặc sắc với phong cách đặc trưng của riêng mình tạo thành “bản hòa tấu 27 chương” - vừa có sự hòa điệu, vừa thể hiện âm sắc độc đáo riêng của từng nhạc cụ. Truyện ngắn của Nguyễn Một thường có giọng điệu phóng khoáng và ẩn chứa tư duy thâm trầm, sâu sắc của nhà văn về những vấn đề nhân sinh. Ông thường khắc họa về mối quan hệ giữa sự sống và cái chết; khắc họa mối quan hệ gắn bó giữa tâm hồn con người và những dòng sông, các miền đất ông đã từng sinh sống. Cái nhìn của nhà văn hướng về sự đa chiều kích trong nội tâm, tính cách nhân vật. Thế giới nhân vật của Nguyễn Một thường có sự giằng xé, mâu thuẫn giữa thiện và ác, cái tầm thường và cái thiêng liêng, cao cả. Truyện ngắn của Nguyễn Trí thấm đẫm chất đời, chất bụi bặm và ẩn chứa chất “muối” của đời sống qua những chi tiết ngổn ngang, bề bộn. Ông thường khắc họa tính cách nhân vật thông qua biểu hiện của hành động, lời nói mà ít miêu tả diễn biến tâm trạng, nội tâm. Người đọc văn của Nguyễn Trí như được sống, trải nghiệm cùng thế giới nhân vật mà ông miêu tả. Theo tôi, Nguyễn Trí là nhà văn của những kiếp người lầm lạc nhưng vẫn giữ trong tâm hồn vẻ đẹp của lương tri và khát vọng sống.",
		},
		{
			name: "Lược Sử Kinh Tế Học",
			category: "Kinh Tế",
			image: "/img/27.jpg",
			price: 135000,
			countInStock: 10,
			brand: "NXB Văn Học",
			rating: 0,
			numReviews: 0,
			description:
				"Lược Sử Kinh Tế Học – Tập truyện ngắn chọn lọc của 3 tác giả họ Nguyễn cùng ở miền Đông: NGUYỄN MỘT, NGUYỄN TRÍ và NGUYỄN HIỆP. Mỗi tác giả góp mặt bằng 9 truyện ngắn đặc sắc với phong cách đặc trưng của riêng mình tạo thành “bản hòa tấu 27 chương” - vừa có sự hòa điệu, vừa thể hiện âm sắc độc đáo riêng của từng nhạc cụ. Truyện ngắn của Nguyễn Một thường có giọng điệu phóng khoáng và ẩn chứa tư duy thâm trầm, sâu sắc của nhà văn về những vấn đề nhân sinh. Ông thường khắc họa về mối quan hệ giữa sự sống và cái chết; khắc họa mối quan hệ gắn bó giữa tâm hồn con người và những dòng sông, các miền đất ông đã từng sinh sống. Cái nhìn của nhà văn hướng về sự đa chiều kích trong nội tâm, tính cách nhân vật. Thế giới nhân vật của Nguyễn Một thường có sự giằng xé, mâu thuẫn giữa thiện và ác, cái tầm thường và cái thiêng liêng, cao cả. Truyện ngắn của Nguyễn Trí thấm đẫm chất đời, chất bụi bặm và ẩn chứa chất “muối” của đời sống qua những chi tiết ngổn ngang, bề bộn. Ông thường khắc họa tính cách nhân vật thông qua biểu hiện của hành động, lời nói mà ít miêu tả diễn biến tâm trạng, nội tâm. Người đọc văn của Nguyễn Trí như được sống, trải nghiệm cùng thế giới nhân vật mà ông miêu tả. Theo tôi, Nguyễn Trí là nhà văn của những kiếp người lầm lạc nhưng vẫn giữ trong tâm hồn vẻ đẹp của lương tri và khát vọng sống.",
		},
		{
			name: "Spy X Family - Tập 7",
			category: "Manga - Comic",
			image: "/img/28.jpg",
			price: 35000,
			countInStock: 50,
			brand: "NXB Kim Đồng",
			rating: 0,
			numReviews: 0,
			description:
				"Cuối cùng thì Twilight cũng tiếp xúc được với mục tiêu Desmond lần đầu tiên bằng cách xen vào cuộc gặp gỡ giữa hắn và cậu con trai thứ Damian!! Liệu thông qua cuộc trò chuyện, Twilight có tìm ra được bản chất của mục tiêu không thể dò xét tâm tư này hay không...!?",
		},
		{
			name: "Chú Thuật Hồi Chiến: Trường Chuyên Chú Thuật Tokyo - Tập 0",
			category: "Manga - Comic",
			image: "/img/29.jpg",
			price: 30000,
			countInStock: 50,
			brand: "NXB Kim Đồng",
			rating: 0,
			numReviews: 0,
			description:
				"Cuối cùng thì Twilight cũng tiếp xúc được với mục tiêu Desmond lần đầu tiên bằng cách xen vào cuộc gặp gỡ giữa hắn và cậu con trai thứ Damian!! Liệu thông qua cuộc trò chuyện, Twilight có tìm ra được bản chất của mục tiêu không thể dò xét tâm tư này hay không...!?",
		},
		{
			name: "Chú Thuật Hồi Chiến: Tập 1",
			category: "Manga - Comic",
			image: "/img/30.jpg",
			price: 30000,
			countInStock: 50,
			brand: "NXB Kim Đồng",
			rating: 0,
			numReviews: 0,
			description:
				"Cuối cùng thì Twilight cũng tiếp xúc được với mục tiêu Desmond lần đầu tiên bằng cách xen vào cuộc gặp gỡ giữa hắn và cậu con trai thứ Damian!! Liệu thông qua cuộc trò chuyện, Twilight có tìm ra được bản chất của mục tiêu không thể dò xét tâm tư này hay không...!?",
		},
		{
			name: "Chú Thuật Hồi Chiến: Tập 2",
			category: "Manga - Comic",
			image: "/img/31.jpg",
			price: 30000,
			countInStock: 50,
			brand: "NXB Kim Đồng",
			rating: 0,
			numReviews: 0,
			description:
				"Cuối cùng thì Twilight cũng tiếp xúc được với mục tiêu Desmond lần đầu tiên bằng cách xen vào cuộc gặp gỡ giữa hắn và cậu con trai thứ Damian!! Liệu thông qua cuộc trò chuyện, Twilight có tìm ra được bản chất của mục tiêu không thể dò xét tâm tư này hay không...!?",
		},
		{
			name: "Người Lạ Bên Bờ Biển - Bản Đặc Biệt",
			category: "Manga - Comic",
			image: "/img/32.jpg",
			price: 80000,
			countInStock: 50,
			brand: "NXB Kim Đồng",
			rating: 0,
			numReviews: 0,
			description:
				"Cuối cùng thì Twilight cũng tiếp xúc được với mục tiêu Desmond lần đầu tiên bằng cách xen vào cuộc gặp gỡ giữa hắn và cậu con trai thứ Damian!! Liệu thông qua cuộc trò chuyện, Twilight có tìm ra được bản chất của mục tiêu không thể dò xét tâm tư này hay không...!?",
		},
		{
			name: "Khi Bạn Đang Mơ Thì Người Khác Đang Nỗ Lực",
			category: "Kỹ Năng Sống",
			image: "/img/33.jpg",
			price: 180000,
			countInStock: 50,
			brand: "NXB Kim Đồng",
			rating: 0,
			numReviews: 0,
			description:
				"Khi Bạn Đang Mơ Thì Người Khác Đang Nỗ Lực - Người khác có thể mang lại cho bạn nhiều lắm là sân khấu, còn vai diễn là do bạn đảm nhiệm. Thế giới này không đợi bạn trưởng thành, cũng chẳng có ai trưởng thành thay bạn, bạn chỉ có thể tự vượt qua gian khổ, tự nỗ lực trưởng thành. Thói quen 'chờ đợi' sẽ ăn mòn sự tự tin, hi vọng và hứng khởi của bạn, bạn chỉ có thể tiếp tục chờ đợi mà thôi. Không lãng phí một giây một phút nào để trưởng thành, thành công sẽ không còn xa nữa. Hãy làm cho mỗi ngày chúng ta sống trên đời này không đơn thuần là một ngày ta già đi, mà là một ngày ta đang trưởng thành hơn. Muốn có một cuộc đời rực rỡ không có gì hối tiếc, chúng ta buộc phải tự tạo ra giá trị và màu sắc vô hạn cho cuộc sống của mình trong thời gian hữu hạn",
		},
		{
			name: "Không Theo Lối Mòn (Tái Bản 2020)",
			category: "Kỹ Năng Sống",
			image: "/img/34.jpg",
			price: 380000,
			countInStock: 50,
			brand: "NXB Tổng Hợp TPHCM",
			rating: 0,
			numReviews: 0,
			description:
				"Không Theo Lối Mòn (Tái Bản 2020) - Người khác có thể mang lại cho bạn nhiều lắm là sân khấu, còn vai diễn là do bạn đảm nhiệm. Thế giới này không đợi bạn trưởng thành, cũng chẳng có ai trưởng thành thay bạn, bạn chỉ có thể tự vượt qua gian khổ, tự nỗ lực trưởng thành. Thói quen 'chờ đợi' sẽ ăn mòn sự tự tin, hi vọng và hứng khởi của bạn, bạn chỉ có thể tiếp tục chờ đợi mà thôi. Không lãng phí một giây một phút nào để trưởng thành, thành công sẽ không còn xa nữa. Hãy làm cho mỗi ngày chúng ta sống trên đời này không đơn thuần là một ngày ta già đi, mà là một ngày ta đang trưởng thành hơn. Muốn có một cuộc đời rực rỡ không có gì hối tiếc, chúng ta buộc phải tự tạo ra giá trị và màu sắc vô hạn cho cuộc sống của mình trong thời gian hữu hạn",
		},
		{
			name: "Chìa Khóa Thành Công (Tái Bản 2021)",
			category: "Kỹ Năng Sống",
			image: "/img/35.jpg",
			price: 280000,
			countInStock: 50,
			brand: "NXB Tổng Hợp TPHCM",
			rating: 0,
			numReviews: 0,
			description:
				"Chìa Khóa Thành Công (Tái Bản 2021) - Người khác có thể mang lại cho bạn nhiều lắm là sân khấu, còn vai diễn là do bạn đảm nhiệm. Thế giới này không đợi bạn trưởng thành, cũng chẳng có ai trưởng thành thay bạn, bạn chỉ có thể tự vượt qua gian khổ, tự nỗ lực trưởng thành. Thói quen 'chờ đợi' sẽ ăn mòn sự tự tin, hi vọng và hứng khởi của bạn, bạn chỉ có thể tiếp tục chờ đợi mà thôi. Không lãng phí một giây một phút nào để trưởng thành, thành công sẽ không còn xa nữa. Hãy làm cho mỗi ngày chúng ta sống trên đời này không đơn thuần là một ngày ta già đi, mà là một ngày ta đang trưởng thành hơn. Muốn có một cuộc đời rực rỡ không có gì hối tiếc, chúng ta buộc phải tự tạo ra giá trị và màu sắc vô hạn cho cuộc sống của mình trong thời gian hữu hạn",
		},
		{
			name: "7 Chiến Lược Thịnh Vượng Và Hạnh Phúc",
			category: "Kỹ Năng Sống",
			image: "/img/36.jpg",
			price: 80000,
			countInStock: 38,
			brand: "NXB Tổng Hợp TPHCM",
			rating: 0,
			numReviews: 0,
			description:
				"7 Chiến Lược Thịnh Vượng Và Hạnh Phúc - Người khác có thể mang lại cho bạn nhiều lắm là sân khấu, còn vai diễn là do bạn đảm nhiệm. Thế giới này không đợi bạn trưởng thành, cũng chẳng có ai trưởng thành thay bạn, bạn chỉ có thể tự vượt qua gian khổ, tự nỗ lực trưởng thành. Thói quen 'chờ đợi' sẽ ăn mòn sự tự tin, hi vọng và hứng khởi của bạn, bạn chỉ có thể tiếp tục chờ đợi mà thôi. Không lãng phí một giây một phút nào để trưởng thành, thành công sẽ không còn xa nữa. Hãy làm cho mỗi ngày chúng ta sống trên đời này không đơn thuần là một ngày ta già đi, mà là một ngày ta đang trưởng thành hơn. Muốn có một cuộc đời rực rỡ không có gì hối tiếc, chúng ta buộc phải tự tạo ra giá trị và màu sắc vô hạn cho cuộc sống của mình trong thời gian hữu hạn",
		},
		{
			name: "Thay Đổi Cuộc Sống Với Nhân Số Học",
			category: "Kỹ Năng Sống",
			image: "/img/37.jpg",
			price: 190000,
			countInStock: 38,
			brand: "NXB Tổng Hợp TPHCM",
			rating: 0,
			numReviews: 0,
			description:
				"Thay Đổi Cuộc Sống Với Nhân Số Học - Người khác có thể mang lại cho bạn nhiều lắm là sân khấu, còn vai diễn là do bạn đảm nhiệm. Thế giới này không đợi bạn trưởng thành, cũng chẳng có ai trưởng thành thay bạn, bạn chỉ có thể tự vượt qua gian khổ, tự nỗ lực trưởng thành. Thói quen 'chờ đợi' sẽ ăn mòn sự tự tin, hi vọng và hứng khởi của bạn, bạn chỉ có thể tiếp tục chờ đợi mà thôi. Không lãng phí một giây một phút nào để trưởng thành, thành công sẽ không còn xa nữa. Hãy làm cho mỗi ngày chúng ta sống trên đời này không đơn thuần là một ngày ta già đi, mà là một ngày ta đang trưởng thành hơn. Muốn có một cuộc đời rực rỡ không có gì hối tiếc, chúng ta buộc phải tự tạo ra giá trị và màu sắc vô hạn cho cuộc sống của mình trong thời gian hữu hạn",
		},
		{
			name: "Rèn Luyện Tư Duy Phản Biện",
			category: "Kỹ Năng Sống",
			image: "/img/38.jpg",
			price: 90000,
			countInStock: 38,
			brand: "NXB Phụ Nữ TPHCM",
			rating: 0,
			numReviews: 0,
			description:
				"Rèn Luyện Tư Duy Phản Biện - Người khác có thể mang lại cho bạn nhiều lắm là sân khấu, còn vai diễn là do bạn đảm nhiệm. Thế giới này không đợi bạn trưởng thành, cũng chẳng có ai trưởng thành thay bạn, bạn chỉ có thể tự vượt qua gian khổ, tự nỗ lực trưởng thành. Thói quen 'chờ đợi' sẽ ăn mòn sự tự tin, hi vọng và hứng khởi của bạn, bạn chỉ có thể tiếp tục chờ đợi mà thôi. Không lãng phí một giây một phút nào để trưởng thành, thành công sẽ không còn xa nữa. Hãy làm cho mỗi ngày chúng ta sống trên đời này không đơn thuần là một ngày ta già đi, mà là một ngày ta đang trưởng thành hơn. Muốn có một cuộc đời rực rỡ không có gì hối tiếc, chúng ta buộc phải tự tạo ra giá trị và màu sắc vô hạn cho cuộc sống của mình trong thời gian hữu hạn",
		},
		{
			name: "Bộ Sách Little Stories (Bộ 10 Cuốn)",
			category: "Kỹ Năng Sống",
			image: "/img/39.jpg",
			price: 690000,
			countInStock: 11,
			brand: "NXB Phụ Nữ TPHCM",
			rating: 0,
			numReviews: 0,
			description:
				"Bộ Sách Little Stories - Người khác có thể mang lại cho bạn nhiều lắm là sân khấu, còn vai diễn là do bạn đảm nhiệm. Thế giới này không đợi bạn trưởng thành, cũng chẳng có ai trưởng thành thay bạn, bạn chỉ có thể tự vượt qua gian khổ, tự nỗ lực trưởng thành. Thói quen 'chờ đợi' sẽ ăn mòn sự tự tin, hi vọng và hứng khởi của bạn, bạn chỉ có thể tiếp tục chờ đợi mà thôi. Không lãng phí một giây một phút nào để trưởng thành, thành công sẽ không còn xa nữa. Hãy làm cho mỗi ngày chúng ta sống trên đời này không đơn thuần là một ngày ta già đi, mà là một ngày ta đang trưởng thành hơn. Muốn có một cuộc đời rực rỡ không có gì hối tiếc, chúng ta buộc phải tự tạo ra giá trị và màu sắc vô hạn cho cuộc sống của mình trong thời gian hữu hạn",
		},
		{
			name: "Bộ Sách Tự Học Và Xử Thế (Bộ 2 Cuốn)",
			category: "Kỹ Năng Sống",
			image: "/img/40.jpg",
			price: 890000,
			countInStock: 11,
			brand: "NXB Phụ Nữ TPHCM",
			rating: 0,
			numReviews: 0,
			description:
				"Bộ Sách Tự Học Và Xử Thế - Người khác có thể mang lại cho bạn nhiều lắm là sân khấu, còn vai diễn là do bạn đảm nhiệm. Thế giới này không đợi bạn trưởng thành, cũng chẳng có ai trưởng thành thay bạn, bạn chỉ có thể tự vượt qua gian khổ, tự nỗ lực trưởng thành. Thói quen 'chờ đợi' sẽ ăn mòn sự tự tin, hi vọng và hứng khởi của bạn, bạn chỉ có thể tiếp tục chờ đợi mà thôi. Không lãng phí một giây một phút nào để trưởng thành, thành công sẽ không còn xa nữa. Hãy làm cho mỗi ngày chúng ta sống trên đời này không đơn thuần là một ngày ta già đi, mà là một ngày ta đang trưởng thành hơn. Muốn có một cuộc đời rực rỡ không có gì hối tiếc, chúng ta buộc phải tự tạo ra giá trị và màu sắc vô hạn cho cuộc sống của mình trong thời gian hữu hạn",
		},
		{
			name: "Giải Thích Ngữ Pháp Tiếng Anh",
			category: "Học Ngoại Ngữ",
			image: "/img/41.jpg",
			price: 290000,
			countInStock: 11,
			brand: "NXB Đà Nẵng",
			rating: 0,
			numReviews: 0,
			description:
				"Ngữ pháp Tiếng Anh tổng hợp các chủ điểm ngữ pháp trọng yếu mà học sinh cần nắm vững. Các chủ điểm ngữ pháp được trình bày rõ ràng, chi tiết. Sau mỗi chủ điểm ngữ pháp là phần bài tập & đáp án nhằm giúp các em củng cố kiến thức đã học, đồng thời tự kiểm tra kết quả. Sách Giải Thích Ngữ Pháp Tiếng Anh, tác Mai Lan Hương – Hà Thanh Uyên, là cuốn sách ngữ pháp đã được phát hành và tái bản rất nhiều lần trong những năm qua. Giải Thích Ngữ Pháp Tiếng Anh được biên soạn thành 9 chương, đề cập đến những vấn đề ngữ pháp từ cơ bản đến nâng cao, phù hợp với mọi trình độ. Các chủ điểm ngữ pháp trong từng chương được biên soạn chi tiết, giải thích cặn kẽ các cách dùng và quy luật mà người học cần nắm vững. Sau mỗi chủ điểm ngữ pháp là phần bài tập đa dạng nhằm giúp người học củng cố lý thuyết. Hy vọng Giải Thích Ngữ Pháp Tiếng Anh sẽ là một quyển sách thiết thực, đáp ứng yêu cầu học, ôn tập và nâng cao trình độ ngữ pháp cho người học và là quyển sách tham khảo bổ ích dành cho giáo viên.",
		},
		{
			name: "The Langmaster - Giải Thích Ngữ Pháp Tiếng Anh (Tái Bản 2021)",
			category: "Học Ngoại Ngữ",
			image: "/img/42.jpg",
			price: 190000,
			countInStock: 11,
			brand: "NXB Đà Nẵng",
			rating: 0,
			numReviews: 0,
			description:
				"Ngữ pháp Tiếng Anh tổng hợp các chủ điểm ngữ pháp trọng yếu mà học sinh cần nắm vững. Các chủ điểm ngữ pháp được trình bày rõ ràng, chi tiết. Sau mỗi chủ điểm ngữ pháp là phần bài tập & đáp án nhằm giúp các em củng cố kiến thức đã học, đồng thời tự kiểm tra kết quả. Sách Giải Thích Ngữ Pháp Tiếng Anh, tác Mai Lan Hương – Hà Thanh Uyên, là cuốn sách ngữ pháp đã được phát hành và tái bản rất nhiều lần trong những năm qua. Giải Thích Ngữ Pháp Tiếng Anh được biên soạn thành 9 chương, đề cập đến những vấn đề ngữ pháp từ cơ bản đến nâng cao, phù hợp với mọi trình độ. Các chủ điểm ngữ pháp trong từng chương được biên soạn chi tiết, giải thích cặn kẽ các cách dùng và quy luật mà người học cần nắm vững. Sau mỗi chủ điểm ngữ pháp là phần bài tập đa dạng nhằm giúp người học củng cố lý thuyết. Hy vọng Giải Thích Ngữ Pháp Tiếng Anh sẽ là một quyển sách thiết thực, đáp ứng yêu cầu học, ôn tập và nâng cao trình độ ngữ pháp cho người học và là quyển sách tham khảo bổ ích dành cho giáo viên.",
		},
		{
			name: "Cẩm Nang Cấu Trúc Tiếng Anh",
			category: "Học Ngoại Ngữ",
			image: "/img/43.jpg",
			price: 90000,
			countInStock: 11,
			brand: "NXB Đại Học Sư Phạm",
			rating: 0,
			numReviews: 0,
			description:
				"Ngữ pháp Tiếng Anh tổng hợp các chủ điểm ngữ pháp trọng yếu mà học sinh cần nắm vững. Các chủ điểm ngữ pháp được trình bày rõ ràng, chi tiết. Sau mỗi chủ điểm ngữ pháp là phần bài tập & đáp án nhằm giúp các em củng cố kiến thức đã học, đồng thời tự kiểm tra kết quả. Sách Giải Thích Ngữ Pháp Tiếng Anh, tác Mai Lan Hương – Hà Thanh Uyên, là cuốn sách ngữ pháp đã được phát hành và tái bản rất nhiều lần trong những năm qua. Giải Thích Ngữ Pháp Tiếng Anh được biên soạn thành 9 chương, đề cập đến những vấn đề ngữ pháp từ cơ bản đến nâng cao, phù hợp với mọi trình độ. Các chủ điểm ngữ pháp trong từng chương được biên soạn chi tiết, giải thích cặn kẽ các cách dùng và quy luật mà người học cần nắm vững. Sau mỗi chủ điểm ngữ pháp là phần bài tập đa dạng nhằm giúp người học củng cố lý thuyết. Hy vọng Giải Thích Ngữ Pháp Tiếng Anh sẽ là một quyển sách thiết thực, đáp ứng yêu cầu học, ôn tập và nâng cao trình độ ngữ pháp cho người học và là quyển sách tham khảo bổ ích dành cho giáo viên.",
		},
		{
			name: "Mindmap English Grammar - Ngữ Pháp Bằng Sơ Đồ Tư Duy",
			category: "Học Ngoại Ngữ",
			image: "/img/44.jpg",
			price: 171000,
			countInStock: 11,
			brand: "NXB Đại Học Sư Phạm",
			rating: 0,
			numReviews: 0,
			description:
				"Ngữ pháp Tiếng Anh tổng hợp các chủ điểm ngữ pháp trọng yếu mà học sinh cần nắm vững. Các chủ điểm ngữ pháp được trình bày rõ ràng, chi tiết. Sau mỗi chủ điểm ngữ pháp là phần bài tập & đáp án nhằm giúp các em củng cố kiến thức đã học, đồng thời tự kiểm tra kết quả. Sách Giải Thích Ngữ Pháp Tiếng Anh, tác Mai Lan Hương – Hà Thanh Uyên, là cuốn sách ngữ pháp đã được phát hành và tái bản rất nhiều lần trong những năm qua. Giải Thích Ngữ Pháp Tiếng Anh được biên soạn thành 9 chương, đề cập đến những vấn đề ngữ pháp từ cơ bản đến nâng cao, phù hợp với mọi trình độ. Các chủ điểm ngữ pháp trong từng chương được biên soạn chi tiết, giải thích cặn kẽ các cách dùng và quy luật mà người học cần nắm vững. Sau mỗi chủ điểm ngữ pháp là phần bài tập đa dạng nhằm giúp người học củng cố lý thuyết. Hy vọng Giải Thích Ngữ Pháp Tiếng Anh sẽ là một quyển sách thiết thực, đáp ứng yêu cầu học, ôn tập và nâng cao trình độ ngữ pháp cho người học và là quyển sách tham khảo bổ ích dành cho giáo viên.",
		},
		{
			name: "Tự Học 2000 Từ Vựng Tiếng Anh Theo Chủ Đề",
			category: "Học Ngoại Ngữ",
			image: "/img/45.jpg",
			price: 71000,
			countInStock: 11,
			brand: "NXB Đại Học Sư Phạm",
			rating: 0,
			numReviews: 0,
			description:
				"Ngữ pháp Tiếng Anh tổng hợp các chủ điểm ngữ pháp trọng yếu mà học sinh cần nắm vững. Các chủ điểm ngữ pháp được trình bày rõ ràng, chi tiết. Sau mỗi chủ điểm ngữ pháp là phần bài tập & đáp án nhằm giúp các em củng cố kiến thức đã học, đồng thời tự kiểm tra kết quả. Sách Giải Thích Ngữ Pháp Tiếng Anh, tác Mai Lan Hương – Hà Thanh Uyên, là cuốn sách ngữ pháp đã được phát hành và tái bản rất nhiều lần trong những năm qua. Giải Thích Ngữ Pháp Tiếng Anh được biên soạn thành 9 chương, đề cập đến những vấn đề ngữ pháp từ cơ bản đến nâng cao, phù hợp với mọi trình độ. Các chủ điểm ngữ pháp trong từng chương được biên soạn chi tiết, giải thích cặn kẽ các cách dùng và quy luật mà người học cần nắm vững. Sau mỗi chủ điểm ngữ pháp là phần bài tập đa dạng nhằm giúp người học củng cố lý thuyết. Hy vọng Giải Thích Ngữ Pháp Tiếng Anh sẽ là một quyển sách thiết thực, đáp ứng yêu cầu học, ôn tập và nâng cao trình độ ngữ pháp cho người học và là quyển sách tham khảo bổ ích dành cho giáo viên.",
		},
		{
			name: "Hackers Ielts: Listening",
			category: "Học Ngoại Ngữ",
			image: "/img/46.jpg",
			price: 171000,
			countInStock: 31,
			brand: "NXB Đại Học Sư Phạm",
			rating: 0,
			numReviews: 0,
			description:
				"Ngữ pháp Tiếng Anh tổng hợp các chủ điểm ngữ pháp trọng yếu mà học sinh cần nắm vững. Các chủ điểm ngữ pháp được trình bày rõ ràng, chi tiết. Sau mỗi chủ điểm ngữ pháp là phần bài tập & đáp án nhằm giúp các em củng cố kiến thức đã học, đồng thời tự kiểm tra kết quả. Sách Giải Thích Ngữ Pháp Tiếng Anh, tác Mai Lan Hương – Hà Thanh Uyên, là cuốn sách ngữ pháp đã được phát hành và tái bản rất nhiều lần trong những năm qua. Giải Thích Ngữ Pháp Tiếng Anh được biên soạn thành 9 chương, đề cập đến những vấn đề ngữ pháp từ cơ bản đến nâng cao, phù hợp với mọi trình độ. Các chủ điểm ngữ pháp trong từng chương được biên soạn chi tiết, giải thích cặn kẽ các cách dùng và quy luật mà người học cần nắm vững. Sau mỗi chủ điểm ngữ pháp là phần bài tập đa dạng nhằm giúp người học củng cố lý thuyết. Hy vọng Giải Thích Ngữ Pháp Tiếng Anh sẽ là một quyển sách thiết thực, đáp ứng yêu cầu học, ôn tập và nâng cao trình độ ngữ pháp cho người học và là quyển sách tham khảo bổ ích dành cho giáo viên.",
		},
		{
			name: "Giáo Trình Chuẩn HSK 1",
			category: "Học Ngoại Ngữ",
			image: "/img/47.jpg",
			price: 191000,
			countInStock: 31,
			brand: "NXB Đại Học Sư Phạm",
			rating: 0,
			numReviews: 0,
			description:
				"Ngữ pháp Tiếng Hoa tổng hợp các chủ điểm ngữ pháp trọng yếu mà học sinh cần nắm vững. Các chủ điểm ngữ pháp được trình bày rõ ràng, chi tiết. Sau mỗi chủ điểm ngữ pháp là phần bài tập & đáp án nhằm giúp các em củng cố kiến thức đã học, đồng thời tự kiểm tra kết quả. Sách Giải Thích Ngữ Pháp Tiếng Anh, tác Mai Lan Hương – Hà Thanh Uyên, là cuốn sách ngữ pháp đã được phát hành và tái bản rất nhiều lần trong những năm qua. Giải Thích Ngữ Pháp Tiếng Anh được biên soạn thành 9 chương, đề cập đến những vấn đề ngữ pháp từ cơ bản đến nâng cao, phù hợp với mọi trình độ. Các chủ điểm ngữ pháp trong từng chương được biên soạn chi tiết, giải thích cặn kẽ các cách dùng và quy luật mà người học cần nắm vững. Sau mỗi chủ điểm ngữ pháp là phần bài tập đa dạng nhằm giúp người học củng cố lý thuyết. Hy vọng Giải Thích Ngữ Pháp Tiếng Anh sẽ là một quyển sách thiết thực, đáp ứng yêu cầu học, ôn tập và nâng cao trình độ ngữ pháp cho người học và là quyển sách tham khảo bổ ích dành cho giáo viên.",
		},
	],
};
export default data;
